# Generated by Django 3.1.2 on 2020-10-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Revenue', 'Дохід'), ('Expense', 'Витрати')], max_length=255, verbose_name='Тип транзакції')),
                ('date_transaction', models.DateField(verbose_name='Дата транзакції')),
                ('description', models.TextField(verbose_name='Опис транзакції')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума транзакції')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Джерело')),
            ],
        ),
    ]
