# Generated by Django 3.1.2 on 2020-10-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_soure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.AlterModelOptions(
            name='transactionsource',
            options={'verbose_name': 'Джерело транзакції', 'verbose_name_plural': 'Джерела транзакцій'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='soure',
            new_name='source',
        ),
    ]
