# Generated by Django 3.1.2 on 2021-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20201010_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(choices=[('Revenue', 'Дохід'), ('Expense', 'Витрати')], max_length=255, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=255, verbose_name='По-батькові')),
                ('amount_of_land', models.CharField(max_length=255, verbose_name='Кількість землі')),
                ('contact_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('note', models.CharField(max_length=255, verbose_name='Нотатки')),
            ],
        ),
    ]
